server:
  port: ${SERVER-PORT:8090}

spring:
  servlet:
    multipart:
      # 上传文件的文件大小
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: ${PROFILES-ACTIVE:dev}
  # 初始化数据库
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml
  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #设置数据库超时时间
      connection-timeout: 100000
      #池中维护的最小连接数
      minimum-idle: 5
      #池中最大连接数
      maximum-pool-size: 15
      #连接最长闲置时间
      idle-timeout: 30000
      #池中连接最长生命周期
      max-lifetime: 30000

#输出日志
logging:
  level:
    org.jeecg.modules.jmreport: debug
    com.edan.report: debug
  config: classpath:log/logback.xml

edan:
  report:
    url: ${REPORT-ADDR:http://localhost:9021}

# 积木报表参数设置
jeecg :
  jmreport:
    #自定义项目前缀
    customPrePath:
    #预览分页自定义
    pageSize:
      - 25
      - 50
      - 100
    #接口超时设置（毫秒）
    connect-timeout: 300000